# Header
menu:
  Home: /
  Tags: /tags
  Archives: /archives
  RSS: /atom.xml
  About: /about

# Content
excerpt_link: read more 
content_max_width: 800px

# Sidebar
author:
  name: Jimmy Wang
  work: DevOps Engineer
  location: Beijign, China
  avatar_url: /images/avatar.jpg

# Links:
links:
  - svg: ./source/svg/github.svg
    url: https://github.com/nnsay

# github comment 
git_commit:
  enable: false
  # client_id: 7fbe80427f54741e289f
  # client_secret: f34ed5fd92e54c9000bd37ba951948cb939deff5
  # repo: sanonz.github.io
  # owner: sanonz
  # admin:
  #   - sanonz
  # per_page: 10


# 百度统计
# baidu:
#   id: e4027971a230b210f4671f485b33846a

# Miscellaneous
rss: /atom.xml
favicon: /images/favicon.ico
