# Header
menu:
  Home: /
  Tags: /tags
  Archives: /archives
  RSS: https://rss.beauty/rss?url=https%3A%2F%2Fnnsay.cn%2Fatom.xml
  About: /about

# Content
excerpt_link: Read more
content_max_width: 800px

# Sidebar
author:
  name: Jimmy Wang
  work: DevOps Engineer
  location: Beijign, China
  avatar_url: /images/avatar.jpg

# Links:
links:
  - svg: ./source/svg/_github.svg
    url: https://github.com/nnsay
  - svg: ./source/svg/_mail.svg
    url: mailto:jimmy.w@aliyun.com

# github comment
git_commit:
  enable: true
  client_id: f9b3c7ac0c057c6a0fa2
  client_secret: 53d6285c56901c86774a7438d5550ef6a25247e4
  repo: blog
  owner: nnsay
  admin:
    - nnsay
  per_page: 10

# https://github.com/wzpan/hexo-generator-search
search:
  path: search.xml
  field: post
  content: true

# https://github.com/hexojs/hexo-generator-sitemap
sitemap:
  path: sitemap.xml
  template: ./sitemap_template.xml
  rel: false

# 百度统计
baidu:
  id: 1f97030bb3a44256d81e14447104bef8

# Miscellaneous
rss: /atom.xml
favicon: /images/favicon.ico
