name: deploy
on:
  push:
    branches:
      - master
jobs:
  hexo-deploymen:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{secrets.GH_TOKEN}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "19"
      - name: install package
        run: npm install
      - name: generate static files
        run: npm run build
      - name: deployment static files
        run: npm run deploy
