name: deploy

on:
  push:
    branches:
      - master
jobs:
  hexo-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"

      - name: use nodejs 19
        uses: actions/setup-node@v3
        with:
          node-version: "19"

      - name: cache npm dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: ${{ runner.OS }}-npm-cache

      - name: install package
        run: npm install

      - name: generate static files
        run: npm run build

      - name: deploy static files
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./public
